In [9]:
import pandas as pd
from os.path import join
"""
os.join est une fonction native de Python qui permet de mettre les bons séparateur dans le chemin d'accès
Fonctionnement : 
    * On importe la fonction avec la commande from os.path import join
    * Appeler join() puis entrer les "()" chaque nom de répertoire dans l'ordre en séparant chaque nom par une ","
"""

In [16]:
date_export = "2024-10-20"
date_export2 = date_export.replace("-", "")
data_file = join("extractions", f"bib_vignettes_{date_export2}.csv.gz")

rbx_bib_qual = pd.read_csv(data_file)
rbx_bib_qual['nb'] = 1

C:\Users\chirliasl\AppData\Local\Temp\ipykernel_10776\598534679.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  rbx_bib_qual = pd.read_csv(data_file)

In [25]:
rbx_bib_qual

,bib_record_id,bib_rbx_date_creation_notice,bib_rbx_support,bib_adresse_electronique,bib_agence_cat,nb
0,1,2014-06-30,Livre,NaN,BnF,1
1,2,2014-06-30,Livre,NaN,BnF,1
2,3,2014-06-30,Livre,NaN,BnF,1
3,4,2014-06-30,Livre,NaN,BnF,1
4,6,2014-06-30,Livre,NaN,BnF,1
...,...,...,...,...,...,...
235955,369656,2024-10-19,Livre,NaN,BnF,1
235956,369657,2024-10-19,Livre,NaN,BnF,1
235957,369658,2024-10-19,Livre,NaN,BnF,1
235958,369659,2024-10-19,Livre,https://www.electre.com/GetBlob.ashx?Ean=97827...,Electre,1
235959,369660,2024-10-19,Livre,https://www.electre.com/GetBlob.ashx?Ean=97827...,Electre,1

In [27]:
len(rbx_bib_qual[rbx_bib_qual['bib_adresse_electronique'].isna()])

223421

In [22]:
rbx_bib_qual.to_csv('')

                                                        nb
bib_adresse_electronique
http://beta.electre.com//GetBlob.asp?Ean=978074...       1
http://beta.electre.com//GetBlob.asp?Ean=978185...       1
http://beta.electre.com//GetBlob.asp?Ean=978202...       1
http://beta.electre.com//GetBlob.asp?Ean=978203...       1
http://beta.electre.com//GetBlob.asp?Ean=978204...       1
...                                                    ...
https://www.gamannecy.com/upload/albums/vfr/004...       1
https://www.gamannecy.com/upload/albums/vin/072...       1
https://www.gamannecy.com/upload/albums/vin/073...       1
lien vers la bibliothèque numérique                      1
NaN                                                 223421

[12276 rows x 1 columns]

In [24]:
rbx_bib_qual.to_csv('tableau_analyse_notices_bib_vignettes_dump_koha_20241020.csv.gz',index=False)