In [12]:
import pandas as pd
from os.path import join

In [13]:
date_export = "2024-08-25"
date_export2 = date_export.replace("-", "")
data_file = join("extractions", f"bib_lang_{date_export2}.csv.gz")


rbx_bib_lang = pd.read_csv(data_file)
rbx_bib_lang['nb'] = 1

C:\Users\pichenotf.NTRBX\AppData\Local\Temp\ipykernel_11704\3610729573.py:6: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  rbx_bib_lang = pd.read_csv(data_file)

In [14]:
rbx_bib_lang.columns

Index(['bib_record_id', 'bib_rbx_support', 'bib_langue_document',
       'bib_langue_originale_document', 'bib_pat', 'bib_title',
       'bib_responsability', 'bib_publication_date_B100',
       'bib_publication_date', 'nb'],
      dtype='object')

In [15]:
rbx_bib_lang.groupby(['bib_langue_document'])['nb'].sum().reset_index().sort_values(by='nb', ascending=False)

         bib_langue_document      nb
252                      fre  216587
104                      eng    4185
0                               2738
306                  fre eng    2403
125                  eng fre     992
..                       ...     ...
382  fre eng ita ger spa dut       1
379      fre eng ita ger dut       1
378      fre eng ita ger           1
376  fre eng ita dut ger spa       1
396              fre eng per       1

[793 rows x 2 columns]

In [16]:
rbx_bib_lang_dut = rbx_bib_lang[rbx_bib_lang['bib_langue_document'].isin(['dut', 'dum'])]
rbx_bib_lang_dut_pat = rbx_bib_lang_dut[rbx_bib_lang_dut['bib_pat'] == True]
rbx_bib_lang_dut_pat

,bib_record_id,bib_rbx_support,bib_langue_document,bib_langue_originale_document,bib_pat,bib_title,bib_responsability,bib_publication_date_B100,bib_publication_date,nb
3493,6282,Livre,dut,NaN,True,De Zeerover poppenkastpel,Minozzoli Gilbert ; Lafaye Georges ; Delannoy ...,1949,NaN,1
3992,7184,Livre,dut,NaN,True,Parijs-Roubaix kroniek van een legende,Sergent Pascal ; De Vlaeminck Roger,1991,NaN,1
3994,7187,Livre,dut,NaN,True,Parijs-Roubaix kroniek van een legende,Sergent Pascal ; De Vlaeminck Roger,1992,NaN,1
4655,8460,Livre,dum,NaN,True,Het Werkende Land opbouw van nederland in mœil...,Van Balen William Julius ; Slingenberg Michel,1936,NaN,1
7032,12375,Livre,dut,NaN,True,Figurenteaterbœken te raadplegen via het europ...,Goormachtigh Ann ; Europees figurenteater centrum,1996,NaN,1
12293,22591,Livre,dum,NaN,True,"Kattestœt Ieper, 12-5-63",Grave Jean-Jacques de ; Dejonghe Albert,1963,NaN,1
13606,25151,Livre,dut,NaN,True,De Avonturen van Pinokkio,Collodi Carlo ; Alberto ; Marzanti Enrico,1950,NaN,1
15267,28149,Livre,dut,NaN,True,"De Touwtjes Los, de Wereld in twintig jaar tea...",Penning Erwin D.-A.,1988,NaN,1
15563,28640,Livre,dum,NaN,True,Theater uit handen Nederlands poppenen schimme...,Bollebakker J.J. ; Sonnemans Gérard ; Nood Mar...,1984,NaN,1
16410,30528,Livre,dut,NaN,True,De Liefde van de Zeven Poppen,Gallico Paul,1990,NaN,1
17215,32509,Livre,dum,NaN,True,Het Huis Blondel van Hendrik Beyaert Warmœsstr...,Loze Pierre ; Vandenbreeden Jos ; La Piscine-M...,1993,NaN,1
21466,41938,Livre,dut,NaN,True,Moving objects,Retel Helmrich Leonard,1990,NaN,1
21472,41944,Livre,dut,NaN,True,Marionetten Samengesteld door,Werumeus Buning Johan Willem Frederik ; Van We...,1925,NaN,1
21490,41962,Livre,dum,NaN,True,Op'toog een poppenspel van Damiët Van Dalsum,Poppentheater Damiët Van Dalsum,1991,NaN,1
23681,45006,Livre,dut,NaN,True,"Histori der nederlandsche vorsten, uit de Huiz...",Van Mieris Frans,1732,NaN,1
23690,45016,Livre,dut,NaN,True,"Histori der nederlandsche vorsten, uit de Huiz...",Van Mieris Frans,1733,NaN,1
23694,45021,Livre,dut,NaN,True,"Histori der nederlandsche vorsten, uit de Huiz...",Van Mieris Frans,1735,NaN,1
23727,45056,Livre,dut,NaN,True,Figurentheater triangel,Bœrwinkel Henk ; Planting Hendrik,1983,NaN,1
24136,45757,Livre,dum,NaN,True,De Hel van het Noorden,NaN,1986,NaN,1
24835,46829,Livre,dut,NaN,True,"Gent, poppenspelstad een bijdrage tot de gesch...",Hoste Lode ; Neirynck Freek,1979,NaN,1
24844,46838,Livre,dut,NaN,True,Pinokkio,Collodi Carlo ; Ilo Jarona,1989,NaN,1
24845,46839,Livre,dut,NaN,True,De Antwerpsche pœsje zijn geschiedenis en zijn...,De Schuyter Jan,1978,NaN,1
25379,47697,Livre,dut,NaN,True,Historie der mirakuleuze Hostien bekent onder ...,Van Mirakel,1770,NaN,1
25513,47925,Livre,dum,NaN,True,De Hel van het Noorden,NaN,1986,NaN,1
26196,49090,Livre,dut,NaN,True,Batavia historisch tafereel uit de XVIIe eeuw,Conscience Hendrik ; Dujardin Edouard,1858,NaN,1
26306,49300,Livre,dut,NaN,True,Het Goudland lotgevallen van dry Vlamingen die...,Conscience Hendrik,1862,NaN,1
26803,50238,Livre,dut,NaN,True,Simon Turchi of de italianen te antwerpen 1550...,Conscience Hendrik,1859,NaN,1
27121,50874,Livre,dut,NaN,True,Das Kaspertheater und seine Entwicklungsgeschi...,Minuth Johannes,1996,NaN,1
28379,52986,Livre,dut,NaN,True,De Loteling,Conscience Hendrik ; Lagye Victor ; Hemeleer J.,1856,NaN,1
28735,53817,Livre,dut,NaN,True,Javanische Schattenspiele 24 abbildungen nach ...,Höver Otto,1923,NaN,1
28852,54100,Livre,dut,NaN,True,Lodewiijk Van Velthem's voortzetting van den s...,Van Velthem's Lodewijk ; Vander Linden Herman ...,1931,NaN,1
29479,55558,Livre,dum,NaN,True,Over de drempel van...het Poppenspe(e)lmuseum,Poppenspeelmuseum,,NaN,1
35352,66677,Livre,dut,NaN,True,Van Jan en Mie globaal lezen voor het Eerste L...,De Vriese P. ; Vanhecke G. ; Nussbaum Felix ; ...,1937,NaN,1
39505,74245,Livre,dum,NaN,True,Blues en andere wereldlijke volksmuziek van de...,Breman Paul ; Woisson Alain,1961,NaN,1
40485,76098,Partition,dut,NaN,True,Nederland's volkslied,Pollmann Jop ; Tiggers Piet ; Woisson Alain,1941,NaN,1
40507,76136,Partition,dut,NaN,True,Nederland's volkslied 282 nederlandse liederen...,Pollmann Jop ; Tiggers Piet ; Woisson Alain,1953,NaN,1
43290,81258,Livre,dut,NaN,True,Marionetten,Gauchat Pierre ; Arnet Edwin,1949,NaN,1
52116,94945,Livre,dut,NaN,True,Pinocchio De Beukelaers's album 125 chromos,NaN,1960,NaN,1
56926,102173,Livre,dut,NaN,True,Lodewijk Van Velthem's voortzetting van den sp...,Van Velthem's Lodewijk ; Vander Linden Herman ...,1906,NaN,1
65997,116855,Livre,dut,NaN,True,Achter de Sigaren-Wolken... [brochure de propa...,Piat Jean,1939,NaN,1
67253,118820,Livre,dut,NaN,True,Musea en de Nord-Pas-de-Calais,Association des conservateurs des musées du No...,1986,NaN,1
71457,125736,Livre,dut,NaN,True,Pinocchio,Collodi Carlo ; Forum des sciences-Centre Fran...,1991,NaN,1
90436,159926,Livre,dut,NaN,True,"McArthurGlen, de grote merken, maar minder duu...",Roubaix,2004,NaN,1
92601,164038,Livre,dut,NaN,True,Désastre de la mer,Juliana,1953,NaN,1
118512,208423,Livre,dut,NaN,True,ABC steden,NaN,,NaN,1
120244,211386,Livre,dut,NaN,True,Apen in huis,Nys Jef,1969,NaN,1
123052,216374,Livre,dut,NaN,True,Buffalo-Bill chromos,Chocolade Martougin,,NaN,1
125956,221390,Livre,dut,NaN,True,Holbeins Oude Testament,Smit Gabriel ; Woisson Alain ; Kips Hans,1954,NaN,1
127577,224423,Livre,dut,NaN,True,De Moderne Vlaamse Houtsnijkunst,Van den Wyngaert Frank ; Havelaar Just ; Maser...,1927,NaN,1
129253,227034,Livre,dut,NaN,True,Ex-libris G. M. van Wees,Acket Désiré ; Bulder Nico ; Le Campion Valentin,,NaN,1
146631,254035,Livre,dut,NaN,True,Vreemden op vertrouwd terrein Het sociaal-cult...,Vanden Borre Saartje,2012,NaN,1
179400,302017,Livre,dut,NaN,True,"Anna, historisch tafereel uit de vlaemsche ges...",Saint Genois Jules de,1844,NaN,1
179401,302019,Livre,dut,NaN,True,Het yzeren graf,Conscience Hendrik ; Dujardin Edward,1863,NaN,1
179453,302080,Livre,dut,NaN,True,Het Vlaemsch in de Kamer Der Volksvertegenwoor...,NaN,1861,NaN,1
179454,302081,Livre,dut,NaN,True,Beknopte uitspraekleer der Nederduitsche tael,Ternest Karel Lodewijk,1860,NaN,1
181672,305001,Livre,dut,NaN,True,Genezende Handen,De Vuyst Achiel,1980,NaN,1
196734,323118,Livre,dut,NaN,True,"Goede raed aen moeders, over de lichamelyke op...","Hufeland, Christoph Wilhelm ; Mauthner von Ma...",1862,NaN,1
208087,336816,Livre,dum,dut,True,De natuerkunde in de volksscholen,Campens Edward ; De Schryver,1857,NaN,1